### ISSUE TITLE
feat(lpms-server): Docker container CI/CD

### ISSUE THREAD

**Issue by kostysh** [windingtree/win-stays#58]
To provide vendors with an easy way of `lpms-server` setup should be implemented the following CI/CD flow:
- build a Docker container;
- publish the container to the docker hub repository;

## Architecture of the docker container

```mermaid
flowchart TD
	subgraph env[Container environment]
		config[Configuration]
	end
	subgraph container[Docker container]
		nginx
		pm2
		lpms-server
		pm2 --> lpms-server
		lpms-server <--> nginx
	end	
	config --> container
	nginx <-- :443 --> HTTPS
```

## Expected CI/CD workflow

```mermaid
sequenceDiagram
	Developer ->> Developer: Sets package version
	Developer ->> Github: Dispatch event "lpms_server_container"
	Github ->> Github: Build container
	Github ->> Hub: Deploy to the Docker hub
	Hub -->> Github: Deployment status
        Github -->> Developer: Action status
```

**Comment by mfw78** [comment]
For the purposes of this container, what is `pm2` ?

**Comment by mfw78** [comment]
IMO, we should not use `pm2` inside a docker container. This can obfuscate the state of the underlying processes from the `docker` engine and/or kubernetes. 

For example, if the `node` process hangs that's running the API, `pm2` would presumably try to restart this, but from the `docker` engine perspective - the system looks healthy and normal. `docker` and/or Kubernetes / related environments are perfectly capable of doing the jobs that `pm2` would otherwise be doing, and providing very good, overall cluster / system monitoring.

I would recommend against using `nginx` within the container as well. Let's keep it *super* simple - just a `node.js` app running and listening to the port(s) that it needs to. Let all the forwarding / system monitoring be done by the platform that's running the container.
